[package]
name = "lnurl-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
cln-rpc = "0.2"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
